# Generated by Django 2.2.16 on 2020-10-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_mcq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_mcq',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
