# Generated by Django 2.2.16 on 2020-10-09 18:04

import account.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('father_name', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=10, null=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('current_status_upsc', models.CharField(blank=True, choices=[('', 'Choose Current Status of UPSC'), ('Student', 'Student'), ('Prelims Attempted', 'Prelims Attempted'), ('Prelims Qualified', 'Prelims Qualified'), ('Mains Attempted', 'Mains Attempted'), ('Mains Qualified', 'Mains Qualified')], max_length=20, null=True)),
                ('is_lateral', models.BooleanField(blank=True, default=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('registered_on', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', account.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Course_Enrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_on', models.DateField()),
                ('is_lateral', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Course Enrolment',
            },
        ),
        migrations.CreateModel(
            name='Mains_Test_Series_Enrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_on', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Mains Test Series Enrolment',
            },
        ),
        migrations.CreateModel(
            name='Scholarship_Test_Enrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_on', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Scholarship Test Enrolment',
            },
        ),
        migrations.CreateModel(
            name='Test_Series_Enrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_on', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Prelims Test Series Enrolment',
            },
        ),
    ]
