# Generated by Django 2.2.16 on 2020-10-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201009_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Educational Qualification'),
        ),
    ]
