# Generated by Django 3.1.1 on 2020-12-11 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20201211_1509'),
        ('account', '0005_auto_20201128_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_enrolment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.batch'),
        ),
    ]
