# Generated by Django 3.1.1 on 2021-02-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_course_enrolment_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admission_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
