# Generated by Django 3.1.1 on 2021-02-06 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210202_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daf',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='daf'),
        ),
        migrations.AddField(
            model_name='user',
            name='interview_quidance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='family_details',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='family_details',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='family_details',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='family_details',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.relation'),
        ),
        migrations.AlterField(
            model_name='family_details',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
