# Generated by Django 3.1.1 on 2021-02-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210206_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='educational_qualification',
            name='course',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
