# Generated by Django 3.1.1 on 2021-12-14 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_educational_qualification_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_fees',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Choose Gender'), ('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='under',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='admission_fees',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='Miscellaneous_Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True)),
                ('paid_date', models.DateTimeField(auto_now=True)),
                ('duration', models.CharField(choices=[('', 'Choose Duration Type'), ('6', 'Six Month'), ('12', 'One Year')], max_length=2)),
                ('type', models.CharField(choices=[('', 'Choose Fee Type'), ('H', 'Hostel Fee'), ('S', 'Study Hall Fee')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
