# Generated by Django 2.2.16 on 2020-10-09 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mains_test_series', '0001_initial'),
        ('tseries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
                ('lesson_plan', models.FileField(blank=True, null=True, upload_to='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_created_by', to=settings.AUTH_USER_MODEL)),
                ('mains_test_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mains_test_series.Mains_Test_Series')),
                ('moderator', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('prelims_test_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tseries.Series')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('test_type', models.CharField(blank=True, choices=[('', 'Choose Test Type'), ('P', 'Prelims'), ('M', 'Mains')], max_length=20, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Part')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=255)),
                ('close_date', models.DateField(default=None)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('material', models.FileField(upload_to='')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='Live_Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateField()),
                ('link', models.URLField()),
                ('password_if_any', models.CharField(blank=True, max_length=30)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Topic')),
            ],
        ),
    ]
