# Generated by Django 2.2.16 on 2020-10-19 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='mains_test_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mains_test_series.Mains_Test_Series'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prelims_test_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tseries.Series'),
        ),
    ]
