# Generated by Django 2.2.16 on 2020-10-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20201019_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.FileField(upload_to='material'),
        ),
    ]
