# Generated by Django 3.1.1 on 2020-12-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20201211_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='live_sessions',
            options={'verbose_name': 'Live Session'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('id',)},
        ),
    ]
