# Generated by Django 3.1.1 on 2021-02-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20201224_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='course',
            name='lesson_plan',
            field=models.FileField(blank=True, null=True, upload_to='course', verbose_name='Brochure'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.FileField(upload_to='profile_photo/material'),
        ),
    ]
