# Generated by Django 2.2.16 on 2020-10-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mains_test_series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mains_test_series',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
