# Generated by Django 2.2.16 on 2020-10-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='on_test',
            options={'verbose_name': 'Live Test', 'verbose_name_plural': 'Live Test'},
        ),
        migrations.AlterField(
            model_name='test',
            name='show_answers',
            field=models.BooleanField(default=True),
        ),
    ]
