# Generated by Django 2.2.16 on 2020-10-14 20:35

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_test', '0002_auto_20201013_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='live_discussion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='live_discussion_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Question Statement'),
        ),
    ]
