# Generated by Django 2.2.16 on 2020-11-03 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_test', '0003_auto_20201014_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['id']},
        ),
    ]
