# Generated by Django 2.2.16 on 2020-11-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_test', '0004_auto_20201103_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='total_marks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
