# Generated by Django 2.2.16 on 2020-10-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tseries', '0002_auto_20201010_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Prelims Test Series', 'verbose_name_plural': 'Prelims Test Series'},
        ),
    ]
