# Generated by Django 2.2.16 on 2020-10-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tseries', '0003_auto_20201013_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
