# Generated by Django 2.2.16 on 2020-10-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afile',
            options={'verbose_name': ' Question File', 'verbose_name_plural': 'Question File'},
        ),
    ]
