# Generated by Django 2.2.16 on 2020-10-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20201010_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afile',
            name='afile',
            field=models.FileField(upload_to='descriptivetfile'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='sfile',
            field=models.FileField(null=True, upload_to='submission'),
        ),
    ]
