# Generated by Django 2.2.16 on 2020-11-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20201023_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('S', 'Not Evaluated'), ('A', 'Evaluated')], max_length=1),
        ),
    ]
