# Generated by Django 3.1.1 on 2021-12-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_auto_20201103_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='sfile',
            field=models.FileField(null=True, upload_to='descriptivetfile'),
        ),
    ]
