# Generated by Django 3.1.1 on 2021-12-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_auto_20211214_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='discussion_video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
